baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'GB Blog'

paginate = 4

[params]
  description = "The most current blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"
